FROM kennethreitz/pipenv

RUN apt-get update -y
RUN apt-get install -y poppler-utils
ADD ./app /app/app
ADD ./testdata /testdata
VOLUME /socks
WORKDIR /app
COPY ./manage.py /app
CMD uvicorn --uds /socks/smlib.sock --log-level debug app.main:app
